export const langMap = [
    { Name: "sitconstract.io", Description: "Arabic", PromoCode:"itpromocode" },
    { Name: "Appvision.com", Description: "Chinese, Mandarin", PromoCode:"itxxpromocode" },
    { Name: "dlobal.com", Description: "Danish", PromoCode:"itpromocode"  },
    { Name: "scrap.io", Description: "Dutch", PromoCode:"itpromocode"  },
    { Name: "scrapper.com", Description: "English, Australian", PromoCode:"itpromocode"  },
    { Name: "addscr.io", Description: "English, British" , PromoCode:"itpromocode" },
    { Name: "newappset.io", Description: "English, Indian", PromoCode:"itpromocode"  },
    { Name: "zxsd.com", Description: "English, US", PromoCode:"itpromocode"  },
    { Name: "asedb.com", Description: "English, Welsh", PromoCode:"itpromocode"  },
    { Name: "new.io", Description: "French" , PromoCode:"itpromocode" },
    { Name: "onetwo.com", Description: "French, Canadian", PromoCode:"itpromocode"  },
    { Name: "pushcode.io", Description: "Hindi", PromoCode:"itpromocode"  },
    { Name: 'codenew.com', Description: 'Hebrew' , PromoCode:"itpromocode" },
    { Name: "alldata.com", Description: "German", PromoCode:"itpromocode"  },
    { Name: "dataset.io", Description: "Icelandic", PromoCode:"itpromocode"  },
    { Name: "appData.io", Description: "Italian" , PromoCode:"itpromocode" },
    { Name: "setnew.io", Description: "Japanese", PromoCode:"itpromocode"  },
    { Name: "kosetonew.io", Description: "Korean" , PromoCode:"itpromocode" },
    { Name: "alldata.com", Description: "Norwegian", PromoCode:"itpromocode"  },
    { Name: "coworker.io", Description: "Polish" , PromoCode:"itpromocode" },
    { Name: "codev.com", Description: "Portuguese", PromoCode:"itpromocode"  },
    { Name: "newDataAll.com", Description: "Portuguese, Brazilian", PromoCode:"itpromocode"  }
  ];